### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by helenehoffmann** [afairless/shap_tutorial#1]
I can't find licence information in this repo. Can this material be altered and reused for (non-commercial) teaching purposes?

**Comment by afairless** [comment]
Hi Helene,

Thank you for raising a good point about the absent license.

I always thought of this repo more as the source material for a blog post and less as a reusable software library.  A user can read the tutorial, write some similar code for themselves, and thereby learn.  Or, if the tutorial doesn't fulfill all of one's needs, one could write one's own supplement and present it alongside my tutorial (or any of the terrific resources that I cite).

Since I thought of it more like a piece of writing, it didn't occur to me that someone would want to modify it directly.  I'm a bit uncomfortable with that, as that's not usually how we treat an article or a book or the like.

On the other hand, you're right that there is code in there, and it might be much more convenient to modify that code rather than to write something similar from scratch.  Could you talk a bit more about your use case and why the "write similar code" or "write a supplement" ideas wouldn't work well for you and your students?

Thank you again for your interest; I'm sorry that I'm being reluctant, but I'm open to persuasion.

Best,
Andrew

**Comment by helenehoffmann** [comment]
Dear Andrew,

thank you so much for your extensive and open answer.

We are planning to do a course on "Explainable AI" in our research center, including tutorials in form of jupyter notebooks. The reasons why I would like to use your notebook are the following:
- It would save me a lot of time developing a notebook by myself
- From my point of view the re-invention of already invented things does not appreciate the effort someone (here: you) already invested. 
- Opening up teaching material, in general, gives the opportunity to improve the material in a collaborative effort
- As we have certain time constraints for the tutorial I would like to adapt the material to our direct needs

To be honest, in my surroundings it is seen as best practice to publish developed code (including notebooks, especially for teaching) for further reuse. I would be highly grateful if someone uses my material for his/her purposes. It shows that someone appreciates the work I've done.

Thinking about it, the best practice to publish your work, is also one reason, why I initially opened that issue. Just for "private" use, I could just have taken the notebook and used it for the course (although I'm not sure if I actually would be allowed to do that!?), but I would rather stick to my own principles. This includes the possibility to publish the adapted tutorial.

OF CAUSE you get full credit for your part in this! Whether published or not.

What do you think? 

Best,
Helene

PS: after reading through your answer again I realized our main difference in perception: you see this as a blog post, I see this as teaching material ;) Maybe we can somehow come together.

**Comment by afairless** [comment]
Hey Helene,

You make a fine case.  I went ahead and added a license to the repo.  From your description, I think it'll be more-than-adequate for your needs.  And if the material does, in fact, turn out to be useful, I'd enjoy hearing about it down the road, if you get a chance.

Happy evening, or whatever suits your time zone,
Andrew

**Comment by helenehoffmann** [comment]
Cool, thanks a lot! I will let you know about the resulting tutorial :)
